name: kac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - emcee=3.1.3
  - wget=1.20.3
  - seaborn=0.12.0
  - ffmpeg=5.0.1
  - astroquery=0.4.6
  - ipykernel=6.16.0
  - ipywidgets==7.7.1
  - corner=2.2.2
  - python-wget=3.2
  - healpy=1.16.1
  - matplotlib=3.6.0
  - papermill=2.4.0
  - pip=22.1.2
  - pytables
  - numpy
  - astropy==5.3.4
  - pandas=1.5.1
  - jupyter
  - ca-certificates
  - certifi
  - filelock
  - openssl
  - gatspy
  - tqdm
  - scikit-learn
  - spiceypy
  - pip:
      - absl-py==1.4.0
      - cloudpickle==2.2.1
      - dm-tree==0.1.8
      - python-dotenv
      - docstring-parser==0.14.1
      - frozendict==2.3.7
      - gast==0.5.4
      - maestrowf==1.1.9
      - markdown-it-py==2.2.0
      - mdurl==0.1.2
      - overrides==7.3.1
      - rich==13.3.4
      - lightkurve
      - aesthetic
