description: # 
    name: clean-analyze
    description: try different cleaning types and then analyze output.

# global.parameters:
#   NSTARS:
#     values: ['10', '10', '20', '20', '30', '30', '40', '40', '50', '50', '60', '60', '70', '70', '80', '80', '90', '90', '100', '100']
#     label: NSTARS.%%
#   PCA:
#     values: ['False', 'True', 'False', 'True', 'False', 'True', 'False', 'True', 'False', 'True', 'False', 'True', 'False', 'True', 'False', 'True', 'False', 'True', 'False', 'True']
#     label: PCA.%%

env:
  variables:
    #Global options.
    OUTPUT_PATH: ../data/maestro/
    OVERWRITE: 'True'
    RANDOM_SEED: 0
    
    # Star cat options
    SAMPLEID: 'brightestnonsat10_rot_mo'
    QUARTER: 12

    # Clean options
    VERBOSE: 'True'
    DVACORR: 'False'
    POSCORR: 'True'
    PCA: 'False'
    PCA_N_COMPS: 10
    READ_FITS: 'False'
    WRITE_CLEAN_DATA: 'True'
    NSTARS: 10

    # Plot centroids options
    PLOT_CENTROID_N: 10 ## number of stars to plot
    # EXTNAME: "FAKE_MOM_RADEC_MODULE_OUTPUT" ## fits ext to read from
    # EXTNAME: "FAKE_GLOB_MOM_DVA_RESIDUAL"
    # EXTNAME: "MOM_RAW_CENTROIDS"
    EXTNAME: "RESIDUALS"
    # EXTNAME: "FAKE_GLOB_MOM_POSCORR_RESIDUAL"
    # EXTNAME: "MOM_POSCORR_RESIDUAL"

    # AVERAGING OPTIONS
    LOCALPOSCORR: 'True'

############################################
study:
    - name: preamble
      description: Activate env.
      run:
        cmd: |
            source ~/.bashrc   
    
    - name: make_clean
      description: Clean the centroids.
      run:
        cmd: |
            echo "Cleaning your data."
            python $(SPECROOT)/../drivers/make_clean.py $(SAMPLEID) \
              --fitsfn $(WORKSPACE)/$(SAMPLEID).fits \
              --read-fits=$(READ_FITS) \
              --write-cleaned-data=$(WRITE_CLEAN_DATA) \
              --dvacorr=$(DVACORR) \
              --use-poscorr=$(POSCORR) \
              --pca=$(PCA) \
              --pca-n-comps=$(PCA_N_COMPS) \
              --max-nstars=$(NSTARS) \
              --verbose=$(VERBOSE) \
              --quarter=$(QUARTER) \
        walltime: '00:30:00'
        procs: 1
        depends: [preamble]
    
    - name: plot_centroids
      description: Plot all centroids as a function of time.
      run:
        cmd: |
            echo "Plotting centroids."
            python $(SPECROOT)/../drivers/plot_centroid_timex.py \
              "$(WORKSPACE)/$(SAMPLEID)_$(EXTNAME)_centroids.pdf" \
              "$(make_clean.workspace)/$(SAMPLEID).fits" \
              --n_samples="$(PLOT_CENTROID_N)" \
              --extname="$(EXTNAME)"
        walltime: '00:30:00'
        procs: 1
        depends: [preamble, make_clean]

    - name: lomb_scargle
      description: Run lomb scargle analysis + plots.
      run:
        cmd: |
            echo "Working on lomb scargle."
            python $(SPECROOT)/../drivers/lomb_scargle_diagnostics.py \
              "$(SAMPLEID)" \
              "$(WORKSPACE)/" \
              "$(make_clean.workspace)/$(SAMPLEID).fits" \
              --n_stars="$(NSTARS)" \
              --extname="$(EXTNAME)" \
              --localposcorr="$(LOCALPOSCORR)"
        walltime: '00:30:00'
        procs: 1
        depends: [preamble, make_clean]
